pool:
  vmImage: ubuntu-16.04

trigger:
- master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Use Node.js 10'

- script: |
    npm run checkchange
    # if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST != "false" ];
  condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['System.PullRequest.PullRequestNumber'], ''))

- script: |
    npm install
    node common/scripts/install-run-rush.js install --bypass-policy
  displayName: 'Install dependencies'

- script: |
    npm run buildci
    npm run bundlesize
  displayName: 'Build'

- script: |
    npm run vrtest
    npm run check-for-changed-files
